Basic nas
SuperDARNCanada/data_flow pull request #13
Opened 2020-10-01 23:16 UTC by mardet987

Here are the four required scripts for the framework I want to start with for using the NAS as the first transfer point and point of long term storage for the Borealis data

2020-11-24 21:21 UTC, kevinkrieger requested changes
I think this is very close to being done, there's just a few things I think need to be addressed, otherwise the code looks great.

2020-11-24 21:21 UTC, kevinkrieger commented on site-linux/borealis_convert_file.py
> +            print("Unable to convert {} to DMAP file.".format(written_array_filename))
should this script be returning non-zero when it fails to convert? Just looking at the convert_and_restructure_daily_on_nas.sh script which depends upon a return value.

2020-11-24 21:21 UTC, kevinkrieger commented on site-linux/rsync_to_sas_from_nas.sh
> +if [ -e ${HOME}/convert_daily_borealis_running ] ; then
same as above, I moved to using a call to ps to determine if the script was running instead of a file lock which failed on me a bunch due to power outages and scripts dying.

2020-11-24 21:21 UTC, kevinkrieger commented on site-linux/rsync_to_sas_from_nas.sh
> +RSYNCRUNNING="`ps aux | grep rsync_to_sas | awk '$11 !~ /grep/ {print $12}'`" #if only this one running, will be /home/transfer/rsync_to_sas /home/transfer/rsync_to_sas
```suggestion
RSYNCRUNNING="`ps aux | grep rsync_to_sas | awk '$11 !~ /grep/ {print $12}'`" #if only this one running, will be /home/transfer/data_flow/site-linux/rsync_to_sas_from_nas /home/transfer/data_flow/site-linux/rsync_to_sas_from_nas.sh
```

2020-11-24 21:21 UTC, kevinkrieger commented on site-linux/rsync_to_sas_from_nas.sh
> +if [[ "$RSYNCRUNNING" == *"data_flow/site-linux/rsync_to_sas"*"data_flow/site-linux/rsync_to_sas"*"data_flow/site-linux/rsync_to_sas"* ]] ; then #must be three times because the first two will be thi
```suggestion
if [[ "$RSYNCRUNNING" == *"data_flow/site-linux/rsync_to_sas_from_nas"*"data_flow/site-linux/rsync_to_sas_from_nas"*"data_flow/site-linux/rsync_to_sas_from_nas"* ]] ; then #must be three times because the first two will be this instance of rsync_to_sas_from_nas
```

2020-11-25 16:51 UTC, kkotyk approved these changes
Its hard for me to tell from review if there are obvious mistakes in bash code, but overall looks good to me.

2020-11-25 16:51 UTC, kkotyk commented on site-linux/convert_and_restructure_daily_on_nas.sh
> +for f in ${RAWACF_CONVERT_FILES}
Could maybe make a function for this and pass in the list of files since this code seems repeated. You could also compress some of this code down by using xargs if you want but its not critical.

2020-11-30 20:18 UTC, mardet987 commented
I'm going to test out this with flock on tcd this week before merging.

2020-11-30 20:21 UTC, mardet987 commented on README.md
> +9,44 0,2,4,6,8,10,12,14,16,18,20,22 * * * flock -n ${HOME}/.data_flow_running -c '${HOME}/data_flow/site-linux/convert_and_restructure_daily_on_nas.sh >> ${HOME}/convert_and_restructure_borealis_log.
```suggestion
9,44 0,2,4,6,8,10,12,14,16,18,20,22 * * * source ~/.bashrc; flock -n ${HOME}/.data_flow_running -c '${HOME}/data_flow/site-linux/convert_and_restructure_daily_on_nas.sh >> ${HOME}/convert_and_restructure_borealis_log.txt 2>&1'
```

2020-12-01 15:35 UTC, kevinkrieger approved these changes

2020-12-01 15:35 UTC, kevinkrieger commented
Woo testing!

2020-12-15 15:33 UTC, merged