Dataflow refining and inotify implementation
SuperDARNCanada/data_flow pull request #23
Opened 2022-09-22 16:44 UTC by tjk584

Pull request modifying dataflow scripts to implement an `inotifywait` daemon in place of crontab. More details are given in the associated Trello cards: 
https://trello.com/c/74fgFOza/67-implement-inotify-for-site-to-campus-dataflow 
https://trello.com/c/rOSTPg5Q/69-refine-dataflow-scripts

2022-10-14 21:24 UTC, kevinkrieger approved these changes

2022-10-14 21:24 UTC, kevinkrieger commented on superdarn-cssdp/convert_on_campus
> +        printf "\nNo files to be converted.\n"
Would this be an error - considering this script should run only if there's a flag generated?

2022-10-14 21:24 UTC, kevinkrieger commented
I think it just needs to lock scripts to only run one at a time and it should be good

2022-10-14 22:09 UTC, tjk584 commented on borealis/rsync_to_nas
> +readonly FILE_THRESHOLD=0.1		# 0.1 min = 6 s
What sort of idea do you have in mind? I could implement the 6 s delay outside this script within the inotify daemon, but I'm not sure how to use inotify to select files not currently being written to

2022-10-14 22:09 UTC, tjk584 commented on inotify_daemons/rsync_to_campus.daemon
> +    if [[ "$FILE" =~ \.convert_and_restructure_flag$ ]]   # Only interested in 2 hour files
I believe it symbolized the end of a line in regular expressions - I don't think its crucial in this case though

2022-10-14 22:09 UTC, tjk584 commented on superdarn-cssdp/convert_on_campus
> +source "${HOME}/.bashrc"
I don't think its used in this script, correct.

2022-10-14 22:09 UTC, tjk584 commented on superdarn-cssdp/convert_on_campus
> +if [[ " ${SITES[*]} " =~ " ${RADAR_ID} " ]]; then
Yeah I think I should be able to implement something within the inotify daemon scripts similar to the `flock` currently used in the crontabs

2022-10-14 22:09 UTC, tjk584 commented on superdarn-cssdp/convert_on_campus
> +        printf "\nNo files to be converted.\n"
I think there could be a case where files fail conversion or transfer earlier along in the dataflow, but the inotify flags continue to trigger subsequent scripts. It would be good to log and notify the engineering dashboard in this case, however

2022-10-18 18:14 UTC, kevinkrieger commented on borealis/rsync_to_nas
> +readonly FILE_THRESHOLD=0.1		# 0.1 min = 6 s
Hmm maybe we should discuss in person

2022-10-18 23:25 UTC, tjk584 commented
Changed rsync_to_nas's filtering to be time-agnostic. The script now filters based on the filename of the script that triggered inotify, instead of waiting for 6 s before taking all older files. This will prevent future problems if Borealis somehow doesn't write to file within the first 6 seconds of a 2-hour block

2022-10-20 21:42 UTC, tjk584 commented
Changed inotify daemon setup: Instead of having individual inotify daemon scripts for each dataflow script, I changed it so each computer has its own inotify daemon script, and all scripts executed on the same computer are triggered by the same daemon. For example, on the site-linux computer, the site-linux daemon executes `convert_and_restructure` and `rsync_to_campus` one after the other within the same script. The single inotify daemon then only has to trigger inotify daemons on other computers, not on the same computer. 

Additionally, I moved all inotify flag handling and references from the data flow scripts to the inotify daemon scripts. This reduces the coupling and complexity of the data flow scripts and allows them to be run on their own without any use of inotify.

2022-10-20 23:37 UTC, kevinkrieger approved these changes
looks good

2022-10-20 23:37 UTC, kevinkrieger commented on inotify_daemons/distribute_borealis_data.daemon
> +        flock -n --verbose $LOCK_FILE $HOME/data_flow/superdarn-cssdp/distribute_borealis_data $RADAR_ID
same here, -c infront of command

2022-10-21 17:42 UTC, tjk584 commented on inotify_daemons/convert_on_campus.daemon
> +        flock -n --verbose $LOCK_FILE $HOME/data_flow/superdarn-cssdp/convert_on_campus $RADAR_ID
I've tested `flock` without using the -c argument, and I believe it works as well. From the man page for `flock`:

```
SYNOPSIS
       flock [options] file|directory command [arguments]
       flock [options] file|directory -c command
```

I did a quick test and verified the following commands are equivalent and both produce a lock correctly:

```
flock -n $LOCK_FILE ./test.sh $ARG1
flock -n $LOCK_FILE -c "./test.sh $ARG1"
```

The only difference I can see is that -c enforced a single argument as a command, so any executable using arguments would have to be contained within quotation marks.

2022-10-21 17:46 UTC, tjk584 commented on inotify_daemons/convert_and_restructure.daemon
> +exec &>> $LOGFILE
Correct, I believe it redirects STDERR to LOGFILE as well. Pretty handy for organizing logs within a script

2022-10-21 17:46 UTC, RemingtonRohel requested changes
Looks really good. There are a few places where testing directories are used, which I assume need to be changed if this is to be pulled on our computers. Once those are addressed I think it will be good to go.

2022-10-21 17:46 UTC, RemingtonRohel commented on inotify_daemons/borealis.daemon
> +exec &>> $LOGFILE
What does this line do?

2022-10-21 17:46 UTC, RemingtonRohel commented on inotify_daemons/borealis.daemon
> +readonly FLAG_OUT="${HOME}/test_data_flow/data_flow/.inotify_flags/.borealis_flag" # For SAS testing
These should be changed for the PR since they are testing values, yes?

2022-10-21 17:46 UTC, RemingtonRohel commented on inotify_daemons/borealis.daemon
> +            $HOME/test_data_flow/data_flow/borealis/rsync_to_nas $FILE # For SAS testing
Another instance of test directory being used.

2022-10-21 17:46 UTC, RemingtonRohel commented on inotify_daemons/campus.daemon
> +# distribute_borealis_data, one after the other#
```suggestion
# distribute_borealis_data, one after the other
```

2022-10-21 17:46 UTC, RemingtonRohel commented on inotify_daemons/campus.daemon
> +readonly FLAG_OUT="${HOME}/test_data_flow/data_flow/.inotify_flags/.campus_dataflow_${RADAR_ID}" # For SAS testing
Test directories, change for PR?

2022-10-21 17:46 UTC, RemingtonRohel commented on inotify_daemons/campus.daemon
> +        # Send out "flag" to trigger next script with inotify (TODO)
What is still TODO with this? It looks like the flag is being written

2022-10-21 17:46 UTC, RemingtonRohel commented on inotify_daemons/site-linux.daemon
> +# Location of inotify watch directory for flags on superdar-cssdp
```suggestion
# Location of inotify watch directory for flags on superdarn-cssdp
```

2022-10-21 17:46 UTC, RemingtonRohel commented on inotify_daemons/site-linux.daemon
> +readonly FLAG_OUT="${HOME}/test_data_flow/data_flow/.inotify_flags/.site-linux_flag_${RADARID}" # For SAS testing
Some more testing directories to be changed?

2022-10-21 17:46 UTC, RemingtonRohel commented on inotify_daemons/site-linux.daemon
> +        $HOME/test_data_flow/data_flow/site-linux/rsync_to_campus # For SAS testing
More test directories

2022-10-21 17:46 UTC, RemingtonRohel commented on library/data_flow_functions.sh
> +	EMAILADDRESS="kevin.krieger@usask.ca"
Probably a good idea to add some more emails to this list, redundancy with notifications never hurts.

2022-10-21 17:46 UTC, RemingtonRohel commented on library/data_flow_functions.sh
> +# Argument 2: Destination file (if on remote computer, specify in argument 3)
Slightly confused by this, can you add an example usage in this comment for both use cases?

2022-10-21 17:46 UTC, RemingtonRohel commented on inotify_daemons/borealis.daemon
> +readonly FLAG_SRC="${HOME}/test_data_flow/data_flow/.inotify_flags" # For SAS testing
Couple of testing directories here

2022-10-21 17:46 UTC, RemingtonRohel commented on inotify_daemons/campus.daemon
> +readonly LOCK_FILE="${HOME}/test_data_flow/data_flow/.${RADAR_ID}_dataflow_lock" # For SAS testing
Couple of testing directories

2022-10-21 17:46 UTC, RemingtonRohel commented on inotify_daemons/campus.daemon
> +readonly REMOTE_FLAG_DEST="${HOME}/test_data_flow/data_flow/.inotify_watchdir" # For SAS testing
Test directory

2022-10-21 17:46 UTC, RemingtonRohel commented on inotify_daemons/campus.daemon
> +readonly FLAG_OUT="${FLAG_SRC}/.campus_dataflow_flag_${RADAR_ID}" # For SAS testing
Testing directories

2022-10-21 17:46 UTC, RemingtonRohel commented on inotify_daemons/campus.daemon
> +        flock -n $LOCK_FILE $HOME/test_data_flow/data_flow/superdarn-cssdp/distribute_borealis_data $RADAR_ID # For SAS testing
Test directories

2022-10-21 17:46 UTC, RemingtonRohel commented on inotify_daemons/site-linux.daemon
> +readonly WATCH_DIR="${HOME}/test_data_flow/data_flow/.inotify_watchdir" # For SAS testing
Test directory

2022-10-21 17:46 UTC, RemingtonRohel commented on inotify_daemons/site-linux.daemon
> +# Location of inotify watch directory for flags on superdar-cssdp. Should match up with
```suggestion
# Location of inotify watch directory for flags on superdarn-cssdp. Should match up with 
```

2022-10-21 17:46 UTC, RemingtonRohel commented on inotify_daemons/site-linux.daemon
> +mkdir -p $FLAG_SRC
Test directories

2022-10-21 17:46 UTC, RemingtonRohel commented on borealis/rsync_to_nas
> +	readonly DEST="/borealis_nfs/testing/inotify_data_flow/daily/" # On NAS	# For SAS testing
Test directory, need to change it for the PR?

2022-10-21 17:46 UTC, RemingtonRohel commented on borealis/rsync_to_nas
> +source "${HOME}/test_data_flow/data_flow/library/data_flow_functions.sh" # For SAS testing
Test directory, need to change it for the PR?

2022-10-21 17:46 UTC, RemingtonRohel commented on site-linux/borealis_convert_file.py
> +from tracemalloc import start
What is this used for? I don't see start used in the changes you made.

2022-10-21 17:46 UTC, RemingtonRohel commented on site-linux/convert_and_restructure
> +source "${HOME}/test_data_flow/data_flow/library/data_flow_functions.sh" # Load in function library # For SAS testing
Test directory

2022-10-21 17:46 UTC, RemingtonRohel commented on site-linux/convert_and_restructure
> +readonly DATA_DIR="/borealis_nfs/testing/inotify_data_flow" # For SAS testing
Test directory

2022-10-21 17:46 UTC, RemingtonRohel commented on site-linux/convert_and_restructure
> +        output=$(python3 ${HOME}/test_data_flow/data_flow/site-linux/remove_record.py ${f}) # For SAS testing
Test directory

2022-10-21 17:46 UTC, RemingtonRohel commented on site-linux/convert_and_restructure
> +        python3 "${HOME}/test_data_flow/data_flow/site-linux/borealis_convert_file.py" --dmap $f # For SAS testing
Test directory

2022-10-21 17:46 UTC, RemingtonRohel commented on site-linux/convert_and_restructure
> +        output=$(python3 ${HOME}/test_data_flow/data_flow/site-linux/remove_record.py ${f}) # For SAS testing
Test dir

2022-10-21 17:46 UTC, RemingtonRohel commented on site-linux/convert_and_restructure
> +        python3 "${HOME}/test_data_flow/data_flow/site-linux/borealis_convert_file.py" $f # For SAS testing
Test dir

2022-10-21 17:46 UTC, RemingtonRohel commented on site-linux/convert_and_restructure
> +        python3 "${HOME}/test_data_flow/data_flow/site-linux/borealis_convert_file.py" $f # For SAS testing
Test dir

2022-10-21 17:46 UTC, RemingtonRohel commented on site-linux/rsync_to_campus
> +readonly DATA_DIR="/borealis_nfs/testing/inotify_data_flow" # For SAS testing
Test dir

2022-10-21 17:46 UTC, RemingtonRohel commented on site-linux/rsync_to_campus
> +	readonly DEST="/sddata/inotify_data_flow/${RADARID}_data/" # For SAS testing
Test dirs

2022-10-21 17:46 UTC, RemingtonRohel commented on superdarn-cssdp/borealis_array_to_dmap.py
> +    # print(sys_call)
Can these be deleted?

2022-10-21 17:46 UTC, RemingtonRohel commented on superdarn-cssdp/convert_on_campus
> +source "${HOME}/test_data_flow/data_flow/library/data_flow_functions.sh"
Test dir

2022-10-21 17:46 UTC, RemingtonRohel commented on superdarn-cssdp/convert_on_campus
> +        python3 "${HOME}/data_flow/test_data_flow/superdarn-cssdp/borealis_array_to_dmap.py" $f # For SAS testing
Test dir

2022-10-21 17:46 UTC, RemingtonRohel commented on superdarn-cssdp/distribute_borealis_data
> +source "${HOME}/test_data_flow/data_flow/library/data_flow_functions.sh"
Test dir

2022-10-21 17:46 UTC, RemingtonRohel commented on superdarn-cssdp/distribute_borealis_data
> +readonly TEST_DIR="${HOME}/test_data_flow" # For SAS testing
Test dir

2022-10-21 17:49 UTC, tjk584 commented on inotify_daemons/borealis.daemon
> +exec &>> $LOGFILE
It redirects STDOUT and STDERR to $LOGFILE for all commands following. Useful for directing log output within a bash script

2022-10-21 17:49 UTC, tjk584 commented on inotify_daemons/borealis.daemon
> +readonly FLAG_OUT="${HOME}/test_data_flow/data_flow/.inotify_flags/.borealis_flag" # For SAS testing
Correct, these will be changed once SAS testing is finished

2022-10-21 17:51 UTC, tjk584 commented on inotify_daemons/campus.daemon
> +        # Send out "flag" to trigger next script with inotify (TODO)
The TODO is for data flow scripts beyond the ones within this repository to use this flag. I'll clarify this in the TODO comment

2022-10-21 18:03 UTC, tjk584 commented on library/data_flow_functions.sh
> +# Argument 2: Destination file (if on remote computer, specify in argument 3)
For verifying on transfers within the same computer (or to a NAS), you just need the absolute path to both files you are comparing. This would be for all local transfers (non-ssh transfers), including transfers between Borealis and the NAS. For example:

```
verify_transfer /data/borealis_data/20221021.1600.00.sas.0.rawacf.hdf5.site /borealis_nfs/borealis_data/backup/20221021.1600.00.sas.0.rawacf.hdf5.site
```

For verifying transfer to a remote computer, you also need to specify the ssh user and address (i.e. radar@10.65.0.32) as well as the absolute path to the file on the remote machine. For example, when transferring from the site NAS to campus:

```
verify_transfer /borealis_nfs/borealis_data/rawacf_array/20221021.1600.00.sas.0.rawacf.hdf5 /sddata/inotify_data_flow/sas_data/20221021.1600.00.sas.0.rawacf.hdf5 mrcopy@128.233.224.39
```

I'll add these examples to the function documentation as well to make it clearer

2022-10-21 18:07 UTC, tjk584 commented on superdarn-cssdp/borealis_array_to_dmap.py
> +    # print(sys_call)
I believe so

2022-10-21 18:09 UTC, tjk584 commented on library/data_flow_functions.sh
> +	EMAILADDRESS="kevin.krieger@usask.ca"
I removed all uses of this email function from the code actually, I could probably delete this function. The plan is to send summary logfiles to the Engineering dashboard and parse them there for any errors or notifications we need

2022-10-21 18:09 UTC, tjk584 commented on site-linux/borealis_convert_file.py
> +from tracemalloc import start
Not sure, might have been a mistake. I'll delete it

2022-10-21 18:35 UTC, RemingtonRohel commented on library/data_flow_functions.sh
> +	EMAILADDRESS="kevin.krieger@usask.ca"
Sounds good. I support deleting the function.

2022-10-21 18:37 UTC, RemingtonRohel commented on library/data_flow_functions.sh
> +# Argument 2: Destination file (if on remote computer, specify in argument 3)
Thanks, that clears it up. I was confused by the argument descriptions in the comment, it sounded like you should specify the destination file as the third argument if you were transferring to a remote computer. With this example I see that I was just reading it wrong

2022-10-25 21:38 UTC, kevinkrieger commented on inotify_daemons/convert_on_campus.daemon
> +        flock -n --verbose $LOCK_FILE $HOME/data_flow/superdarn-cssdp/convert_on_campus $RADAR_ID
Ah! I misread the man page

2022-10-25 21:49 UTC, kevinkrieger approved these changes
I looked through the changes since Thursday, looks great

2022-11-22 19:58 UTC, kevinkrieger reviewed
These review comments are from last week, I wasn't completed yet but I'll pass them to you now so you have them

2022-11-22 21:09 UTC, tjk584 commented on borealis/rsync_to_nas
> +readonly RADARID=$(hostname | cut --characters 1-3)
It's in the .bashrc for all site linux computers, but not the Borealis computers. We could change this though, to make it consistent across all computers.

2022-11-22 21:10 UTC, tjk584 commented on borealis/rsync_to_nas
> +readonly LOGGING_DIR="${HOME}/logs/rsync_to_nas/$(date +%Y)/$(date +%m)"
Nice, that looks a lot cleaner

2022-11-22 21:11 UTC, tjk584 commented on borealis/rsync_to_nas
> +# Ensure that only a single instance of this script runs.
That's a good point, I think it would with the way I currently parse for summary data. I'll change this

2022-11-22 21:18 UTC, tjk584 commented on site-linux/antennas_iq_backlog
> +readonly LOW_MEMORY_SITES=("pgr" "inv" "rkn")
Will do, must have missed that

2022-11-22 21:20 UTC, tjk584 commented on inotify_daemons/borealis.daemon
> +# Inotify is triggered multiple times as multiple 2-hour site files are created. We only want to
For certain experiments, multiple rawacf/antennas_iq files are generated too, so the script would still trigger for each of those files

2022-11-23 18:51 UTC, tjk584 commented on README.md
> +    - If the data flow can use the NAS at a site
Yes, I missed this for some reason

2023-01-09 15:43 UTC, kevinkrieger approved these changes
Was 15 seconds causing an issue somewhere? Just curious - changes look good to me

2023-01-09 21:55 UTC, tjk584 commented
> Was 15 seconds causing an issue somewhere? Just curious - changes look good to me

It caused the `rsync_to_nas` script to sometimes execute twice when 2f sound experiments ran. I don't think it caused any major problems though, at least none that showed up in the downtimes.

2023-01-09 22:06 UTC, merged