Antennas iq
SuperDARNCanada/data_flow pull request #47
Opened 2024-04-17 16:34 UTC by Doreban

Added antennas iq plotting to the data flow.

On the site computers:
- Added an if statement in the `site-linux.daemon` to run the borealis-data-utils `plot_antennas_iq ` function if it exists to create iq plots.
- Added to `rsync_to_campus` a check to find generated iq plots and transfer to the dataman user on campus. 

On the campus computers:
- created a `archive_iq_plots` to compress files that are over a day old into thumbnail images. Reducing the data size of each image from ~50 KB to ~ 2 KB.
- Amended `campus.daemon` to run `archive_iq_plots`.

Currently the addition of iq plots into the data flow is dependant on the borealis-data-utils repo. If reviewers think that the iq plotting should be rewritten into the data flow repo let me know.

2024-04-18 18:40 UTC, tjk584 reviewed
Looks pretty good so far, one suggestion:
- I think the antennas iq plotting script should be moved to this repo. Logging for this script should be made similar to the other dataflow scripts too, so we can easily know when/why plots don't make it to the dashboard.

2024-04-18 18:40 UTC, tjk584 commented on campus/archive_iq_plots
> +#   - convert linux utility
Is this installed via zypper?

2024-04-18 18:40 UTC, tjk584 commented on campus/archive_iq_plots
> +readonly SUMMARY_FILE="${SUMMARY_DIR}/${RADAR_ID}.$(date -u +%Y%m%d).archive_iq.log"
Summary file was initially created for logs that are sent to logman for getting stats for the dashboard. We may not need these for this script.

2024-04-18 18:40 UTC, tjk584 commented on inotify_daemons/site-linux.daemon
> +        fi
I think we should add this script to the data_flow repo, since this is the only place it will be run in our regular operations

2024-04-18 19:40 UTC, Doreban commented on campus/archive_iq_plots
> +#   - convert linux utility
I believe it is default on at least opensuse operating systems. All computers I've checked on have had convert

2024-04-19 20:36 UTC, Doreban commented
Moved the iq plotting that was done in borealis-data-utils into the site-linux section of the data flow. I am not certain of how much of the new plotting scripts I added are absolutely required for the plotting, but I pulled the functions that were used and stitched it together and made sure it works the same as it did in the borealis-data-utils branch.

2024-04-26 15:29 UTC, Doreban commented on site-linux/rsync_to_campus
> +  if [[ $eturn_value -eq 0 ]]; then
Yeah, but that's because it just interpreted the misspelled variable as empty so it passed the condition.

2024-04-26 15:38 UTC, Doreban commented on site-linux/plot_antennas_iq
> +readonly FAILED_RESIZE_DEST=${HOME}/logging/daily_plots/failed_resize/
I'll move it over then. I just wasn't sure if they should be still kept under logging or not.

2024-04-26 17:15 UTC, tjk584 requested changes
Looks good, just one typo to fix

2024-04-26 17:15 UTC, tjk584 commented on README.md
> +finishes executing.
```suggestion
4. site-linux/rsync_to_campus: Moves rawacf DMAP, array files, and antennas iq plots from the site storage to 
the university campus server at sdc-serv. Triggered via site-linux.daemon when plot_antennas_iq
finishes executing. 
```

2024-04-26 17:15 UTC, tjk584 commented on site-linux/plot_antennas_iq
> +readonly FAILED_RESIZE_DEST=${HOME}/logs/daily_plots/failed_resize/
```suggestion
readonly PLOT_DEST=${HOME}/logs/daily_plots/
readonly FULLSIZE_DEST=${PLOT_DEST}/fullsize/
readonly FAILED_RESIZE_DEST=${PLOT_DEST}/failed_resize/
```

2024-04-26 17:27 UTC, tjk584 approved these changes

2024-04-26 17:28 UTC, merged